select * from tblJobInfo;
-- 1개월차
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (3, to_date('2020-08-12','yyyy-mm-dd'), '미가입', '계약직', '백엔드 개발', 2600, 3);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (7, to_date('2020-08-08','yyyy-mm-dd'), '가입', '정규직', '자체 솔루션', 2750, 7);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (9, to_date('2020-08-20','yyyy-mm-dd'), '미가입', '계약직', 'DB 개발', 2800, 9);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (10, to_date('2020-08-23','yyyy-mm-dd'), '가입', '정규직', 'DB 개발', 2500, 10);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (12, to_date('2020-08-15','yyyy-mm-dd'), '가입', '정규직', '프론트엔드 개발', 2800, 12);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (14, to_date('2020-08-17','yyyy-mm-dd'), '미가입', '계약직', '유지보수 SM', 2800, 14);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (16, to_date('2020-08-19','yyyy-mm-dd'), '가입', '계약직', '유지보수 SM', 2800, 16);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (20, to_date('2020-08-19','yyyy-mm-dd'), '가입', '정규직', 'IT 영업', 2800, 20);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (22, to_date('2020-08-22','yyyy-mm-dd'), '미가입', '계약직', 'DB 개발', 2500, 22);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (25, to_date('2020-08-20','yyyy-mm-dd'), '가입', '정규직', '자체 솔루션', 2800, 25);
-- 2개월차
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (5, to_date('2020-09-01','yyyy-mm-dd'), '가입', '정규직', '프론트엔드 개발', 2600, 5);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (8, to_date('2020-09-14','yyyy-mm-dd'), '가입', '정규직', '유지보수 SM', 2800, 8);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (11, to_date('2020-09-11','yyyy-mm-dd'), '가입', '정규직', '웹개발 SI', 2600, 11);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (15, to_date('2020-08-26','yyyy-mm-dd'), '가입', '계약직', '웹개발 SI', 2500, 15);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (18, to_date('2020-09-04','yyyy-mm-dd'), '미가입', '계약직', 'IT기획', 2750, 18);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (19, to_date('2020-09-21','yyyy-mm-dd'), '미가입', '계약직', '자체 솔루션', 2500, 19);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (21, to_date('2020-09-05','yyyy-mm-dd'), '가입', '계약직', '자체 솔루션', 2800, 21);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (23, to_date('2020-09-15','yyyy-mm-dd'), '미가입', '계약직', '자체 솔루션', 2600, 23);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (26, to_date('2020-09-19','yyyy-mm-dd'), '가입', '정규직', 'IT기획', 2800, 26);
-- 3개월차
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (4, to_date('2020-09-30','yyyy-mm-dd'), '미가입', '계약직', '유지보수 SM', 2500, 4);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (24, to_date('2020-10-07','yyyy-mm-dd'), '가입', '정규직', '백엔드 개발', 2800, 24);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (27, to_date('2020-10-05','yyyy-mm-dd'), '가입', '계약직', '프론트엔드 개발', 2800, 27);

-- 더미정보

insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-08','yyyy-mm-dd'), '미가입', '인턴', 'IT 영업', 2500, 30);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-18','yyyy-mm-dd'), '가입', '계약직', 'IT 영업', 2500, 31);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-17','yyyy-mm-dd'), '가입', '전환형 인턴', '자체 솔루션', 2800, 32);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-01','yyyy-mm-dd'), '가입', '아르바이트', 'DB 개발', 2600, 33);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-19','yyyy-mm-dd'), '가입', '계약직', '자체 솔루션', 2900, 34);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-12','yyyy-mm-dd'), '가입', '정규직', 'DB 개발', 2500, 35);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-06','yyyy-mm-dd'), '가입', '정규직', '유지보수 SM', 2900, 36);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-02','yyyy-mm-dd'), '가입', '아르바이트', 'IT 영업', 2800, 37);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-02','yyyy-mm-dd'), '가입', '정규직', '백엔드 개발', 2750, 38);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-01','yyyy-mm-dd'), '가입', '계약직', 'IT기획', 2800, 39);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-22','yyyy-mm-dd'), '가입', '전환형 인턴', '프론트엔드 개발', 2500, 40);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-08','yyyy-mm-dd'), '가입', '정규직', '자체 솔루션', 2500, 41);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-25','yyyy-mm-dd'), '가입', '아르바이트', 'DB 개발', 2800, 42);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-13','yyyy-mm-dd'), '가입', '아르바이트', 'IT 영업', 2500, 43);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-25','yyyy-mm-dd'), '가입', '정규직', 'DB 개발', 2900, 44);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-10','yyyy-mm-dd'), '가입', '인턴', '백엔드 개발', 3000, 45);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-04','yyyy-mm-dd'), '가입', '전환형 인턴', '자체 솔루션', 2800, 46);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-04','yyyy-mm-dd'), '가입', '아르바이트', '웹개발 SI', 2600, 47);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-08','yyyy-mm-dd'), '가입', '계약직', '프론트엔드 개발', 2800, 48);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-11','yyyy-mm-dd'), '가입', '계약직', '프론트엔드 개발', 2900, 49);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-19','yyyy-mm-dd'), '가입', '정규직', 'DB 개발', 2750, 50);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-06','yyyy-mm-dd'), '가입', '전환형 인턴', '자체 솔루션', 2500, 51);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-12','yyyy-mm-dd'), '가입', '계약직', 'IT기획', 2500, 52);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-26','yyyy-mm-dd'), '가입', '계약직', 'DB 개발', 3000, 53);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-15','yyyy-mm-dd'), '미가입', '계약직', '프론트엔드 개발', 2500, 54);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-22','yyyy-mm-dd'), '미가입', '계약직', '웹개발 SI', 2500, 55);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-13','yyyy-mm-dd'), '가입', '아르바이트', 'DB 개발', 3000, 56);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-13','yyyy-mm-dd'), '가입', '정규직', 'IT 영업', 2800, 57);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-21','yyyy-mm-dd'), '가입', '아르바이트', '웹개발 SI', 2800, 58);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-13','yyyy-mm-dd'), '가입', '정규직', '웹개발 SI', 2500, 59);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-16','yyyy-mm-dd'), '가입', '아르바이트', 'IT기획', 2750, 60);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-18','yyyy-mm-dd'), '가입', '계약직', 'IT기획', 2500, 61);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-10','yyyy-mm-dd'), '가입', '전환형 인턴', 'IT 영업', 2800, 62);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-01','yyyy-mm-dd'), '미가입', '전환형 인턴', '웹개발 SI', 2600, 63);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-03','yyyy-mm-dd'), '가입', '전환형 인턴', 'IT기획', 3000, 64);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-15','yyyy-mm-dd'), '가입', '전환형 인턴', 'IT기획', 2500, 65);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-09','yyyy-mm-dd'), '가입', '전환형 인턴', 'DB 개발', 2900, 66);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-17','yyyy-mm-dd'), '가입', '정규직', '웹개발 SI', 2900, 67);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-14','yyyy-mm-dd'), '가입', '아르바이트', '자체 솔루션', 2600, 68);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-05','yyyy-mm-dd'), '가입', '계약직', 'IT기획', 2600, 69);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-15','yyyy-mm-dd'), '가입', '정규직', '웹개발 SI', 2900, 70);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-13','yyyy-mm-dd'), '가입', '인턴', '백엔드 개발', 2500, 71);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-03','yyyy-mm-dd'), '미가입', '전환형 인턴', '유지보수 SM', 2500, 72);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-06','yyyy-mm-dd'), '미가입', '인턴', 'IT기획', 2900, 73);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-25','yyyy-mm-dd'), '가입', '정규직', '프론트엔드 개발', 2500, 74);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-02','yyyy-mm-dd'), '미가입', '아르바이트', 'IT 영업', 2500, 75);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-11','yyyy-mm-dd'), '가입', '정규직', 'IT기획', 2600, 76);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-16','yyyy-mm-dd'), '미가입', '아르바이트', '자체 솔루션', 2500, 77);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-25','yyyy-mm-dd'), '가입', '계약직', '웹개발 SI', 3000, 78);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-21','yyyy-mm-dd'), '가입', '인턴', '프론트엔드 개발', 2500, 79);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-01','yyyy-mm-dd'), '가입', '계약직', '백엔드 개발', 2500, 80);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-14','yyyy-mm-dd'), '가입', '정규직', 'IT 영업', 2500, 81);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-16','yyyy-mm-dd'), '가입', '정규직', '자체 솔루션', 2600, 82);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-11','yyyy-mm-dd'), '가입', '정규직', '자체 솔루션', 3000, 83);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-12','yyyy-mm-dd'), '가입', '인턴', '프론트엔드 개발', 2800, 84);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-02','yyyy-mm-dd'), '가입', '인턴', '유지보수 SM', 2600, 85);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-28','yyyy-mm-dd'), '미가입', '아르바이트', 'IT 영업', 2500, 86);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-10','yyyy-mm-dd'), '미가입', '인턴', 'DB 개발', 2750, 87);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-05','yyyy-mm-dd'), '가입', '전환형 인턴', '자체 솔루션', 2900, 88);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-21','yyyy-mm-dd'), '가입', '정규직', '웹개발 SI', 2900, 89);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-01','yyyy-mm-dd'), '가입', '전환형 인턴', '자체 솔루션', 2900, 90);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-09','yyyy-mm-dd'), '가입', '정규직', 'IT 영업', 2500, 91);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-07','yyyy-mm-dd'), '가입', '전환형 인턴', '백엔드 개발', 2600, 92);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-24','yyyy-mm-dd'), '가입', '정규직', '웹개발 SI', 2500, 93);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-18','yyyy-mm-dd'), '미가입', '전환형 인턴', '프론트엔드 개발', 2750, 94);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-09','yyyy-mm-dd'), '가입', '전환형 인턴', 'DB 개발', 2750, 95);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-10','yyyy-mm-dd'), '가입', '정규직', 'DB 개발', 2500, 96);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-28','yyyy-mm-dd'), '가입', '전환형 인턴', '자체 솔루션', 2750, 97);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-25','yyyy-mm-dd'), '가입', '아르바이트', 'IT 영업', 2750, 98);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-16','yyyy-mm-dd'), '미가입', '아르바이트', '자체 솔루션', 2800, 99);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-04','yyyy-mm-dd'), '가입', '전환형 인턴', '웹개발 SI', 2500, 100);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-20','yyyy-mm-dd'), '미가입', '정규직', '웹개발 SI', 2500, 101);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-25','yyyy-mm-dd'), '가입', '계약직', 'DB 개발', 3000, 102);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-09','yyyy-mm-dd'), '가입', '계약직', '자체 솔루션', 2800, 103);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-07','yyyy-mm-dd'), '미가입', '계약직', 'IT 영업', 2500, 104);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-06','yyyy-mm-dd'), '가입', '아르바이트', 'IT 영업', 2900, 105);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-17','yyyy-mm-dd'), '가입', '인턴', '웹개발 SI', 2600, 106);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-18','yyyy-mm-dd'), '미가입', '인턴', 'IT 영업', 2600, 107);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-17','yyyy-mm-dd'), '가입', '인턴', 'IT기획', 2800, 108);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-08','yyyy-mm-dd'), '가입', '전환형 인턴', '백엔드 개발', 2750, 109);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-21','yyyy-mm-dd'), '가입', '전환형 인턴', '유지보수 SM', 3000, 110);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-16','yyyy-mm-dd'), '가입', '계약직', 'DB 개발', 2900, 111);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-25','yyyy-mm-dd'), '미가입', '계약직', '백엔드 개발', 2600, 112);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-17','yyyy-mm-dd'), '가입', '정규직', 'IT 영업', 3000, 113);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-01','yyyy-mm-dd'), '가입', '아르바이트', '백엔드 개발', 2600, 114);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-10','yyyy-mm-dd'), '가입', '정규직', '프론트엔드 개발', 2900, 115);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-05','yyyy-mm-dd'), '가입', '전환형 인턴', '자체 솔루션', 2800, 116);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-18','yyyy-mm-dd'), '가입', '계약직', '프론트엔드 개발', 2500, 117);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-22','yyyy-mm-dd'), '가입', '아르바이트', '프론트엔드 개발', 2800, 118);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-17','yyyy-mm-dd'), '가입', '정규직', 'IT기획', 2750, 119);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-21','yyyy-mm-dd'), '가입', '계약직', 'IT기획', 2600, 120);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-22','yyyy-mm-dd'), '가입', '정규직', 'IT 영업', 2600, 121);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-18','yyyy-mm-dd'), '미가입', '정규직', 'IT 영업', 2600, 122);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-14','yyyy-mm-dd'), '가입', '인턴', '웹개발 SI', 2500, 123);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-28','yyyy-mm-dd'), '가입', '인턴', '유지보수 SM', 3000, 124);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-14','yyyy-mm-dd'), '미가입', '정규직', '프론트엔드 개발', 2800, 125);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-24','yyyy-mm-dd'), '가입', '전환형 인턴', '백엔드 개발', 2800, 126);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-28','yyyy-mm-dd'), '가입', '인턴', '자체 솔루션', 2500, 127);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-28','yyyy-mm-dd'), '가입', '계약직', '자체 솔루션', 2900, 128);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-22','yyyy-mm-dd'), '가입', '정규직', '프론트엔드 개발', 3000, 129);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-20','yyyy-mm-dd'), '가입', '계약직', 'IT기획', 3000, 130);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-14','yyyy-mm-dd'), '가입', '아르바이트', 'DB 개발', 2900, 131);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-20','yyyy-mm-dd'), '가입', '계약직', '프론트엔드 개발', 2500, 132);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-08','yyyy-mm-dd'), '가입', '전환형 인턴', '프론트엔드 개발', 2750, 133);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-10','yyyy-mm-dd'), '미가입', '전환형 인턴', '유지보수 SM', 2600, 134);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-11','yyyy-mm-dd'), '가입', '아르바이트', 'IT 영업', 2900, 135);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-17','yyyy-mm-dd'), '가입', '정규직', '유지보수 SM', 2500, 136);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-17','yyyy-mm-dd'), '가입', '전환형 인턴', '백엔드 개발', 2500, 137);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-09','yyyy-mm-dd'), '가입', '계약직', '백엔드 개발', 2500, 138);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-14','yyyy-mm-dd'), '미가입', '인턴', 'IT 영업', 2900, 139);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-05','yyyy-mm-dd'), '가입', '계약직', '자체 솔루션', 2500, 140);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-09','yyyy-mm-dd'), '미가입', '전환형 인턴', '프론트엔드 개발', 2600, 141);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-03','yyyy-mm-dd'), '가입', '정규직', '프론트엔드 개발', 2750, 142);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-25','yyyy-mm-dd'), '가입', '전환형 인턴', 'IT기획', 3000, 143);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-08','yyyy-mm-dd'), '가입', '아르바이트', 'DB 개발', 2600, 144);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-09','yyyy-mm-dd'), '가입', '계약직', '프론트엔드 개발', 2500, 145);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-24','yyyy-mm-dd'), '가입', '아르바이트', '유지보수 SM', 2750, 146);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-04','yyyy-mm-dd'), '가입', '계약직', '프론트엔드 개발', 2750, 147);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-22','yyyy-mm-dd'), '미가입', '전환형 인턴', '자체 솔루션', 2750, 148);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-11','yyyy-mm-dd'), '가입', '전환형 인턴', '자체 솔루션', 2750, 149);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-15','yyyy-mm-dd'), '가입', '정규직', '백엔드 개발', 2900, 150);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-14','yyyy-mm-dd'), '가입', '전환형 인턴', '프론트엔드 개발', 3000, 151);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-23','yyyy-mm-dd'), '가입', '전환형 인턴', 'IT 영업', 2600, 152);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-21','yyyy-mm-dd'), '가입', '전환형 인턴', '유지보수 SM', 3000, 153);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-05','yyyy-mm-dd'), '가입', '계약직', 'IT 영업', 2600, 154);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-21','yyyy-mm-dd'), '미가입', '정규직', 'IT기획', 2800, 155);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-13','yyyy-mm-dd'), '가입', '인턴', 'IT 영업', 2600, 156);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-12','yyyy-mm-dd'), '가입', '전환형 인턴', '웹개발 SI', 2900, 157);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-25','yyyy-mm-dd'), '가입', '전환형 인턴', '웹개발 SI', 2800, 158);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-08','yyyy-mm-dd'), '가입', '계약직', '유지보수 SM', 2500, 159);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-03','yyyy-mm-dd'), '가입', '정규직', 'IT 영업', 2800, 160);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-11','yyyy-mm-dd'), '미가입', '아르바이트', 'IT기획', 2800, 161);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-03','yyyy-mm-dd'), '가입', '전환형 인턴', '웹개발 SI', 2500, 162);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-26','yyyy-mm-dd'), '가입', '정규직', 'IT 영업', 2500, 163);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-15','yyyy-mm-dd'), '가입', '아르바이트', '유지보수 SM', 3000, 164);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-25','yyyy-mm-dd'), '가입', '계약직', '백엔드 개발', 2500, 165);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-06','yyyy-mm-dd'), '가입', '전환형 인턴', '웹개발 SI', 2500, 166);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-25','yyyy-mm-dd'), '가입', '계약직', '웹개발 SI', 2750, 167);
insert into tblJobInfo (seq, startDate, insurance, form, career, income, completNum) values (seqJobInfo.nextval, to_date('2020-12-26','yyyy-mm-dd'), '가입', '아르바이트', '유지보수 SM', 2800, 168);
