-- tblCourseConsultation 수업상담 테이블
-- 수강생의 상담 정보


Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-06-19', '수업이 너무 쉽게 느껴짐', 87, 3, 63);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-09-3', '오라클에 어려움을 느낌', 38, 2, 245);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-10-17', '그만두고 싶어함', 38, 4, 37);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-11-29', '오라클에 어려움을 느낌', 116, 1, 293);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-08-3', '수업이 너무 쉽게 느껴짐', 125, 5, 126);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-10-23', '수업이 너무 쉽게 느껴짐', 117, 5, 269);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-06-30', '자바에 어려움을 느낌', 145, 5, 390);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-06-29', '자바에 어려움을 느낌', 33, 5, 69);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-06-26', '인생에 어려움을 느낌', 45, 5, 3);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-11-22', '수업이 너무 쉽게 느껴짐', 11, 2, 130);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-06-26', '수업이 너무 쉽게 느껴짐', 59, 5, 358);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-09-1', '진도를 따라가기 힘들어함', 95, 4, 159);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-07-1', '수업이 너무 쉽게 느껴짐', 25, 5, 38);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-07-10', '인생에 어려움을 느낌', 99, 4, 356);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-11-13', '그만두고 싶어함', 134, 4, 362);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-09-8', '인생에 어려움을 느낌', 87, 3, 16);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-09-18', '인생에 어려움을 느낌', 116, 5, 382);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-08-17', '자바에 어려움을 느낌', 23, 5, 96);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-06-30', '오라클에 어려움을 느낌', 20, 3, 361);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-06-30', '진도를 따라가기 힘들어함', 149, 3, 248);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-08-15', '자바에 어려움을 느낌', 112, 1, 31);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-10-13', '인생에 어려움을 느낌', 97, 1, 38);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-06-3', '그만두고 싶어함', 73, 5, 171);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-09-12', '그만두고 싶어함', 131, 3, 115);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-08-26', '진도를 따라가기 힘들어함', 127, 3, 354);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-11-27', '수업이 너무 쉽게 느껴짐', 61, 4, 3);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-06-30', '자바에 어려움을 느낌', 135, 3, 36);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-06-22', '자바에 어려움을 느낌', 75, 3, 65);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-09-14', '진도를 따라가기 힘들어함', 148, 4, 380);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-07-6', '진도를 따라가기 힘들어함', 68, 4, 70);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-11-14', '오라클에 어려움을 느낌', 16, 3, 269);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-06-17', '진도를 따라가기 힘들어함', 152, 2, 257);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-09-14', '진도를 따라가기 힘들어함', 97, 3, 308);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-09-18', '그만두고 싶어함', 145, 3, 222);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-10-6', '오라클에 어려움을 느낌', 38, 5, 362);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-08-8', '인생에 어려움을 느낌', 20, 5, 305);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-11-19', '자바에 어려움을 느낌', 89, 4, 1);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-07-4', '그만두고 싶어함', 31, 4, 281);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-10-19', '인생에 어려움을 느낌', 77, 1, 148);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-08-25', '오라클에 어려움을 느낌', 42, 2, 79);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-08-5', '인생에 어려움을 느낌', 79, 3, 313);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-06-7', '수업이 너무 쉽게 느껴짐', 136, 4, 38);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-09-25', '자바에 어려움을 느낌', 103, 5, 80);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-08-10', '진도를 따라가기 힘들어함', 132, 1, 266);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-11-19', '진도를 따라가기 힘들어함', 85, 3, 354);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-11-1', '자바에 어려움을 느낌', 102, 1, 211);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-11-20', '수업이 너무 쉽게 느껴짐', 86, 3, 100);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-06-25', '그만두고 싶어함', 110, 1, 353);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-10-2', '수업이 너무 쉽게 느껴짐', 94, 5, 84);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-10-6', '자바에 어려움을 느낌', 53, 2, 383);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-10-2', '수업이 너무 쉽게 느껴짐', 92, 1, 392);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-06-6', '오라클에 어려움을 느낌', 48, 2, 353);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-11-7', '그만두고 싶어함', 155, 1, 179);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-06-15', '수업이 너무 쉽게 느껴짐', 110, 5, 136);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-07-8', '진도를 따라가기 힘들어함', 125, 1, 50);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-10-7', '오라클에 어려움을 느낌', 55, 5, 26);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-10-26', '진도를 따라가기 힘들어함', 32, 4, 216);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-06-24', '수업이 너무 쉽게 느껴짐', 140, 2, 268);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-07-4', '그만두고 싶어함', 27, 1, 88);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-09-8', '인생에 어려움을 느낌', 108, 1, 186);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-11-28', '그만두고 싶어함', 95, 4, 41);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-09-19', '그만두고 싶어함', 106, 5, 315);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-11-17', '오라클에 어려움을 느낌', 119, 3, 96);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-11-22', '인생에 어려움을 느낌', 25, 2, 239);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-10-25', '인생에 어려움을 느낌', 138, 2, 203);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-06-1', '진도를 따라가기 힘들어함', 66, 1, 338);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-07-2', '그만두고 싶어함', 150, 4, 354);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-08-5', '자바에 어려움을 느낌', 10, 5, 88);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-09-3', '오라클에 어려움을 느낌', 148, 2, 119);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-07-27', '진도를 따라가기 힘들어함', 79, 5, 17);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-07-26', '진도를 따라가기 힘들어함', 88, 2, 228);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-09-24', '수업이 너무 쉽게 느껴짐', 9, 1, 260);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-06-2', '그만두고 싶어함', 16, 3, 161);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-09-15', '진도를 따라가기 힘들어함', 11, 2, 133);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-09-4', '인생에 어려움을 느낌', 130, 2, 60);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-07-27', '수업이 너무 쉽게 느껴짐', 160, 1, 80);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-09-29', '오라클에 어려움을 느낌', 48, 1, 368);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-11-22', '오라클에 어려움을 느낌', 16, 2, 205);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-08-9', '그만두고 싶어함', 148, 2, 193);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-08-22', '오라클에 어려움을 느낌', 154, 5, 12);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-10-30', '진도를 따라가기 힘들어함', 70, 2, 76);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-08-28', '자바에 어려움을 느낌', 26, 2, 56);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-09-16', '오라클에 어려움을 느낌', 19, 4, 57);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-06-3', '오라클에 어려움을 느낌', 98, 5, 54);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-07-15', '그만두고 싶어함', 133, 1, 282);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-06-4', '오라클에 어려움을 느낌', 98, 2, 324);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-11-23', '인생에 어려움을 느낌', 127, 5, 347);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-10-28', '인생에 어려움을 느낌', 65, 1, 236);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-07-22', '그만두고 싶어함', 32, 2, 386);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-06-26', '수업이 너무 쉽게 느껴짐', 67, 1, 176);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-09-17', '그만두고 싶어함', 29, 1, 29);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-08-6', '진도를 따라가기 힘들어함', 35, 5, 205);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-06-22', '그만두고 싶어함', 40, 2, 168);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-10-23', '자바에 어려움을 느낌', 56, 4, 378);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-09-7', '오라클에 어려움을 느낌', 77, 1, 342);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-10-22', '인생에 어려움을 느낌', 17, 3, 119);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-07-13', '인생에 어려움을 느낌', 17, 2, 165);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-11-1', '오라클에 어려움을 느낌', 58, 4, 48);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-08-25', '오라클에 어려움을 느낌', 115, 1, 205);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-07-10', '인생에 어려움을 느낌', 119, 4, 138);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-11-4', '오라클에 어려움을 느낌', 109, 1, 31);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-07-7', '진도를 따라가기 힘들어함', 70, 1, 162);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-10-10', '진도를 따라가기 힘들어함', 114, 5, 119);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-08-12', '진도를 따라가기 힘들어함', 159, 5, 115);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-08-6', '오라클에 어려움을 느낌', 111, 5, 251);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-09-13', '수업이 너무 쉽게 느껴짐', 116, 5, 254);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-06-22', '인생에 어려움을 느낌', 75, 1, 91);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-07-1', '오라클에 어려움을 느낌', 147, 2, 288);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-08-22', '인생에 어려움을 느낌', 104, 3, 113);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-08-12', '오라클에 어려움을 느낌', 33, 1, 97);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-11-17', '인생에 어려움을 느낌', 2, 2, 320);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-06-16', '그만두고 싶어함', 126, 2, 338);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-06-6', '자바에 어려움을 느낌', 76, 5, 71);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-06-28', '그만두고 싶어함', 133, 3, 348);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-09-7', '인생에 어려움을 느낌', 56, 1, 365);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-07-29', '오라클에 어려움을 느낌', 10, 2, 21);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-08-22', '오라클에 어려움을 느낌', 13, 3, 196);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-08-16', '오라클에 어려움을 느낌', 92, 2, 107);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-11-13', '자바에 어려움을 느낌', 80, 2, 263);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-11-16', '수업이 너무 쉽게 느껴짐', 98, 1, 296);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-07-12', '오라클에 어려움을 느낌', 30, 2, 205);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-10-12', '오라클에 어려움을 느낌', 32, 1, 302);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-11-28', '진도를 따라가기 힘들어함', 45, 3, 150);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-07-20', '수업이 너무 쉽게 느껴짐', 113, 4, 122);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-10-7', '자바에 어려움을 느낌', 48, 2, 106);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-08-4', '인생에 어려움을 느낌', 139, 3, 52);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-07-1', '그만두고 싶어함', 146, 2, 383);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-08-22', '오라클에 어려움을 느낌', 64, 4, 394);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-08-7', '그만두고 싶어함', 151, 4, 161);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-08-9', '그만두고 싶어함', 25, 1, 153);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-07-26', '자바에 어려움을 느낌', 32, 4, 106);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-06-6', '자바에 어려움을 느낌', 154, 3, 150);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-08-15', '수업이 너무 쉽게 느껴짐', 37, 1, 41);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-07-24', '오라클에 어려움을 느낌', 67, 2, 255);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-07-18', '그만두고 싶어함', 90, 3, 284);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-09-22', '인생에 어려움을 느낌', 75, 1, 332);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-06-10', '진도를 따라가기 힘들어함', 44, 2, 136);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-06-16', '자바에 어려움을 느낌', 68, 4, 209);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-06-27', '수업이 너무 쉽게 느껴짐', 3, 1, 29);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-06-3', '진도를 따라가기 힘들어함', 124, 2, 59);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-08-23', '진도를 따라가기 힘들어함', 128, 5, 36);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-07-29', '인생에 어려움을 느낌', 55, 5, 80);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-07-1', '수업이 너무 쉽게 느껴짐', 29, 3, 210);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-10-6', '수업이 너무 쉽게 느껴짐', 152, 3, 114);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-06-16', '진도를 따라가기 힘들어함', 49, 3, 117);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-06-7', '수업이 너무 쉽게 느껴짐', 22, 1, 58);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-11-5', '진도를 따라가기 힘들어함', 75, 5, 131);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-07-9', '진도를 따라가기 힘들어함', 105, 2, 78);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-06-9', '인생에 어려움을 느낌', 116, 5, 207);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-07-7', '진도를 따라가기 힘들어함', 156, 5, 269);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-10-23', '오라클에 어려움을 느낌', 112, 2, 86);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-08-28', '진도를 따라가기 힘들어함', 153, 5, 207);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-07-26', '오라클에 어려움을 느낌', 155, 2, 251);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-06-13', '진도를 따라가기 힘들어함', 35, 2, 119);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-07-21', '자바에 어려움을 느낌', 12, 2, 96);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-08-8', '인생에 어려움을 느낌', 21, 5, 130);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-08-7', '수업이 너무 쉽게 느껴짐', 151, 1, 143);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-10-2', '인생에 어려움을 느낌', 101, 3, 104);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-09-15', '인생에 어려움을 느낌', 5, 5, 10);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-08-26', '그만두고 싶어함', 37, 3, 216);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-08-19', '그만두고 싶어함', 59, 3, 288);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-10-10', '수업이 너무 쉽게 느껴짐', 30, 5, 13);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-11-1', '인생에 어려움을 느낌', 59, 1, 377);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-11-13', '오라클에 어려움을 느낌', 52, 4, 45);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-11-22', '자바에 어려움을 느낌', 59, 3, 6);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-11-3', '인생에 어려움을 느낌', 7, 1, 149);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-10-1', '수업이 너무 쉽게 느껴짐', 113, 1, 180);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-10-6', '수업이 너무 쉽게 느껴짐', 46, 1, 208);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-09-21', '진도를 따라가기 힘들어함', 8, 2, 375);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-09-15', '진도를 따라가기 힘들어함', 59, 3, 335);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-10-11', '그만두고 싶어함', 73, 4, 97);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-09-5', '오라클에 어려움을 느낌', 123, 3, 16);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-06-23', '진도를 따라가기 힘들어함', 149, 5, 202);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-10-26', '자바에 어려움을 느낌', 117, 2, 170);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-11-26', '오라클에 어려움을 느낌', 136, 4, 359);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-06-12', '오라클에 어려움을 느낌', 72, 2, 140);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-09-9', '그만두고 싶어함', 21, 1, 213);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-08-20', '수업이 너무 쉽게 느껴짐', 111, 1, 211);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-10-14', '진도를 따라가기 힘들어함', 13, 3, 44);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-06-14', '그만두고 싶어함', 126, 5, 98);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-09-1', '오라클에 어려움을 느낌', 90, 5, 238);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-06-16', '오라클에 어려움을 느낌', 131, 5, 9);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-08-8', '그만두고 싶어함', 125, 3, 87);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-07-3', '진도를 따라가기 힘들어함', 39, 4, 192);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-10-13', '수업이 너무 쉽게 느껴짐', 118, 1, 188);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-08-4', '수업이 너무 쉽게 느껴짐', 45, 5, 282);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-11-11', '오라클에 어려움을 느낌', 90, 3, 46);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-07-17', '자바에 어려움을 느낌', 79, 1, 293);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-08-23', '오라클에 어려움을 느낌', 124, 1, 214);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-11-24', '자바에 어려움을 느낌', 70, 1, 262);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-09-6', '인생에 어려움을 느낌', 70, 2, 328);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-10-9', '수업이 너무 쉽게 느껴짐', 160, 1, 319);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-07-30', '오라클에 어려움을 느낌', 94, 3, 209);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-09-12', '오라클에 어려움을 느낌', 9, 2, 395);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-09-3', '자바에 어려움을 느낌', 4, 1, 59);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-09-16', '진도를 따라가기 힘들어함', 5, 1, 350);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-07-30', '오라클에 어려움을 느낌', 112, 1, 6);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-10-18', '자바에 어려움을 느낌', 17, 4, 311);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-09-10', '자바에 어려움을 느낌', 86, 3, 254);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-07-5', '수업이 너무 쉽게 느껴짐', 71, 4, 382);
Insert into tblCourseConsultation (seq, consultdate, content, makeSubjectNum, reasonNum, regiNum)values (SEQCOURSECONSULTATION.nextval, '2020-09-14', '인생에 어려움을 느낌', 67, 2, 297);
