-- tblJobConsultation 취업상담 테이블
-- 수강생의 취업 상담 내용

Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '빈도수 높은 면접질문을 알려주었음', 93, '2020-07-13');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '자소서 수정을 해주었음', 372, '2020-09-7');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '포트폴리오 수정을 해주었음', 168, '2020-06-9');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '면접 노하우를 알려주었다', 296, '2020-11-16');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '자소서 수정을 해주었음', 297, '2020-06-18');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '빈도수 높은 면접질문을 알려주었음', 105, '2020-07-23');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '자소서 수정을 해주었음', 228, '2020-09-21');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '빈도수 높은 면접질문을 알려주었음', 258, '2020-08-1');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '빈도수 높은 면접질문을 알려주었음', 205, '2020-08-25');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '포트폴리오 수정을 해주었음', 168, '2020-08-13');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '빈도수 높은 면접질문을 알려주었음', 54, '2020-11-14');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '자소서 수정을 해주었음', 360, '2020-11-10');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '포트폴리오 수정을 해주었음', 310, '2020-06-28');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '면접 노하우를 알려주었다', 265, '2020-11-11');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '빈도수 높은 면접질문을 알려주었음', 338, '2020-10-26');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '빈도수 높은 면접질문을 알려주었음', 30, '2020-09-7');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '빈도수 높은 면접질문을 알려주었음', 155, '2020-10-26');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '자소서 수정을 해주었음', 155, '2020-10-15');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '포트폴리오 수정을 해주었음', 165, '2020-06-11');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '포트폴리오 수정을 해주었음', 96, '2020-10-26');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '포트폴리오 수정을 해주었음', 367, '2020-10-15');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '면접 태도에 대한 교정', 183, '2020-06-6');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '면접 태도에 대한 교정', 51, '2020-06-19');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '포트폴리오 수정을 해주었음', 246, '2020-08-2');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '면접 태도에 대한 교정', 331, '2020-06-5');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '빈도수 높은 면접질문을 알려주었음', 130, '2020-11-18');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '면접 태도에 대한 교정', 318, '2020-08-25');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '면접 노하우를 알려주었다', 368, '2020-10-1');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '포트폴리오 수정을 해주었음', 278, '2020-10-11');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '면접 노하우를 알려주었다', 361, '2020-08-12');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '포트폴리오 수정을 해주었음', 319, '2020-08-24');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '자소서 수정을 해주었음', 89, '2020-09-16');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '포트폴리오 수정을 해주었음', 207, '2020-08-28');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '면접 노하우를 알려주었다', 164, '2020-10-8');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '면접 태도에 대한 교정', 396, '2020-08-30');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '포트폴리오 수정을 해주었음', 86, '2020-06-20');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '면접 태도에 대한 교정', 350, '2020-10-12');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '자소서 수정을 해주었음', 133, '2020-09-29');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '빈도수 높은 면접질문을 알려주었음', 115, '2020-08-12');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '포트폴리오 수정을 해주었음', 278, '2020-07-23');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '자소서 수정을 해주었음', 392, '2020-06-24');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '면접 노하우를 알려주었다', 216, '2020-11-6');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '포트폴리오 수정을 해주었음', 379, '2020-10-13');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '포트폴리오 수정을 해주었음', 320, '2020-07-24');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '면접 태도에 대한 교정', 282, '2020-10-3');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '면접 노하우를 알려주었다', 226, '2020-07-18');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '면접 노하우를 알려주었다', 359, '2020-08-9');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '면접 태도에 대한 교정', 58, '2020-08-14');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '빈도수 높은 면접질문을 알려주었음', 315, '2020-10-11');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '면접 태도에 대한 교정', 308, '2020-09-6');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '면접 노하우를 알려주었다', 179, '2020-10-14');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '자소서 수정을 해주었음', 238, '2020-11-13');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '포트폴리오 수정을 해주었음', 204, '2020-10-5');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '자소서 수정을 해주었음', 279, '2020-11-28');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '면접 노하우를 알려주었다', 391, '2020-09-6');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '포트폴리오 수정을 해주었음', 212, '2020-10-8');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '면접 노하우를 알려주었다', 169, '2020-11-17');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '자소서 수정을 해주었음', 159, '2020-11-24');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '면접 태도에 대한 교정', 209, '2020-11-16');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '면접 노하우를 알려주었다', 220, '2020-11-8');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '면접 태도에 대한 교정', 54, '2020-09-21');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '빈도수 높은 면접질문을 알려주었음', 218, '2020-10-11');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '면접 태도에 대한 교정', 29, '2020-11-14');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '면접 노하우를 알려주었다', 34, '2020-08-3');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '빈도수 높은 면접질문을 알려주었음', 372, '2020-08-7');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '자소서 수정을 해주었음', 272, '2020-10-9');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '자소서 수정을 해주었음', 190, '2020-07-22');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '포트폴리오 수정을 해주었음', 251, '2020-08-21');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '자소서 수정을 해주었음', 331, '2020-06-15');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '면접 노하우를 알려주었다', 194, '2020-10-7');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '면접 노하우를 알려주었다', 211, '2020-07-26');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '면접 태도에 대한 교정', 196, '2020-09-8');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '빈도수 높은 면접질문을 알려주었음', 240, '2020-06-19');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '면접 태도에 대한 교정', 124, '2020-06-30');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '면접 태도에 대한 교정', 149, '2020-10-11');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '포트폴리오 수정을 해주었음', 392, '2020-08-30');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '면접 노하우를 알려주었다', 30, '2020-08-3');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '포트폴리오 수정을 해주었음', 340, '2020-08-15');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '면접 노하우를 알려주었다', 277, '2020-10-29');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '면접 노하우를 알려주었다', 232, '2020-10-22');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '면접 태도에 대한 교정', 302, '2020-09-21');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '면접 태도에 대한 교정', 331, '2020-06-18');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '빈도수 높은 면접질문을 알려주었음', 320, '2020-08-15');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '포트폴리오 수정을 해주었음', 82, '2020-08-4');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '면접 태도에 대한 교정', 385, '2020-11-13');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '포트폴리오 수정을 해주었음', 376, '2020-10-30');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '면접 노하우를 알려주었다', 380, '2020-07-2');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '포트폴리오 수정을 해주었음', 268, '2020-10-24');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '포트폴리오 수정을 해주었음', 337, '2020-11-21');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '면접 노하우를 알려주었다', 114, '2020-11-28');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '면접 태도에 대한 교정', 106, '2020-10-2');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '포트폴리오 수정을 해주었음', 375, '2020-07-4');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '면접 노하우를 알려주었다', 230, '2020-10-8');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '빈도수 높은 면접질문을 알려주었음', 181, '2020-07-11');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '포트폴리오 수정을 해주었음', 324, '2020-09-11');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '포트폴리오 수정을 해주었음', 62, '2020-08-10');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '면접 태도에 대한 교정', 397, '2020-08-20');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '자소서 수정을 해주었음', 328, '2020-08-16');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '포트폴리오 수정을 해주었음', 61, '2020-07-13');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '면접 태도에 대한 교정', 150, '2020-07-1');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '면접 태도에 대한 교정', 176, '2020-08-8');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '포트폴리오 수정을 해주었음', 207, '2020-11-26');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '면접 노하우를 알려주었다', 374, '2020-11-21');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '면접 노하우를 알려주었다', 238, '2020-06-14');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '포트폴리오 수정을 해주었음', 66, '2020-11-19');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '포트폴리오 수정을 해주었음', 21, '2020-06-15');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '면접 태도에 대한 교정', 229, '2020-07-27');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '자소서 수정을 해주었음', 126, '2020-06-20');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '포트폴리오 수정을 해주었음', 129, '2020-09-24');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '빈도수 높은 면접질문을 알려주었음', 351, '2020-06-9');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '면접 태도에 대한 교정', 253, '2020-09-5');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '빈도수 높은 면접질문을 알려주었음', 89, '2020-10-14');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '포트폴리오 수정을 해주었음', 133, '2020-09-23');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '자소서 수정을 해주었음', 350, '2020-11-1');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '빈도수 높은 면접질문을 알려주었음', 250, '2020-09-25');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '면접 태도에 대한 교정', 364, '2020-10-11');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '면접 노하우를 알려주었다', 93, '2020-07-11');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '자소서 수정을 해주었음', 170, '2020-08-9');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '면접 태도에 대한 교정', 243, '2020-09-4');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '빈도수 높은 면접질문을 알려주었음', 94, '2020-07-10');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '빈도수 높은 면접질문을 알려주었음', 326, '2020-10-10');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '면접 노하우를 알려주었다', 73, '2020-06-21');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '포트폴리오 수정을 해주었음', 73, '2020-06-13');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '빈도수 높은 면접질문을 알려주었음', 80, '2020-07-21');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '빈도수 높은 면접질문을 알려주었음', 149, '2020-11-28');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '면접 노하우를 알려주었다', 216, '2020-10-16');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '면접 태도에 대한 교정', 164, '2020-07-15');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '자소서 수정을 해주었음', 380, '2020-09-18');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '면접 노하우를 알려주었다', 201, '2020-09-7');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '면접 태도에 대한 교정', 350, '2020-10-5');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '면접 태도에 대한 교정', 330, '2020-06-21');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '면접 노하우를 알려주었다', 56, '2020-08-11');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '면접 태도에 대한 교정', 316, '2020-06-17');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '자소서 수정을 해주었음', 333, '2020-10-7');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '포트폴리오 수정을 해주었음', 122, '2020-10-21');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '빈도수 높은 면접질문을 알려주었음', 242, '2020-06-29');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '면접 노하우를 알려주었다', 353, '2020-11-18');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '자소서 수정을 해주었음', 210, '2020-07-11');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '포트폴리오 수정을 해주었음', 122, '2020-10-14');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '빈도수 높은 면접질문을 알려주었음', 274, '2020-09-16');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '면접 노하우를 알려주었다', 148, '2020-11-26');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '면접 노하우를 알려주었다', 114, '2020-06-14');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '면접 노하우를 알려주었다', 94, '2020-11-24');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '면접 태도에 대한 교정', 188, '2020-10-20');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '자소서 수정을 해주었음', 127, '2020-09-12');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '면접 노하우를 알려주었다', 381, '2020-11-29');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '면접 노하우를 알려주었다', 274, '2020-11-3');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '면접 태도에 대한 교정', 301, '2020-07-29');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '자소서 수정을 해주었음', 353, '2020-08-19');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '면접 노하우를 알려주었다', 205, '2020-06-8');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '포트폴리오 수정을 해주었음', 316, '2020-07-8');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '자소서 수정을 해주었음', 43, '2020-09-18');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '자소서 수정을 해주었음', 70, '2020-07-19');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '포트폴리오 수정을 해주었음', 261, '2020-09-11');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '면접 태도에 대한 교정', 269, '2020-11-7');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '면접 태도에 대한 교정', 8, '2020-11-3');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '포트폴리오 수정을 해주었음', 260, '2020-10-15');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '포트폴리오 수정을 해주었음', 339, '2020-11-15');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '자소서 수정을 해주었음', 238, '2020-11-7');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '자소서 수정을 해주었음', 221, '2020-09-21');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '면접 태도에 대한 교정', 57, '2020-11-30');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '면접 태도에 대한 교정', 128, '2020-11-30');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '빈도수 높은 면접질문을 알려주었음', 37, '2020-10-2');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '포트폴리오 수정을 해주었음', 32, '2020-10-17');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '포트폴리오 수정을 해주었음', 176, '2020-11-19');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '포트폴리오 수정을 해주었음', 156, '2020-08-14');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '면접 태도에 대한 교정', 63, '2020-11-21');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '자소서 수정을 해주었음', 320, '2020-10-13');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '포트폴리오 수정을 해주었음', 171, '2020-09-4');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '빈도수 높은 면접질문을 알려주었음', 308, '2020-08-7');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '면접 태도에 대한 교정', 197, '2020-10-3');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '면접 노하우를 알려주었다', 229, '2020-06-8');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '포트폴리오 수정을 해주었음', 183, '2020-10-3');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '면접 노하우를 알려주었다', 110, '2020-08-28');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '면접 노하우를 알려주었다', 345, '2020-11-28');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '면접 태도에 대한 교정', 51, '2020-07-14');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '면접 태도에 대한 교정', 269, '2020-11-16');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '면접 노하우를 알려주었다', 345, '2020-10-16');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '빈도수 높은 면접질문을 알려주었음', 167, '2020-11-16');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '빈도수 높은 면접질문을 알려주었음', 53, '2020-10-6');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '포트폴리오 수정을 해주었음', 268, '2020-08-19');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '면접 노하우를 알려주었다', 208, '2020-11-27');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '자소서 수정을 해주었음', 215, '2020-10-20');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '빈도수 높은 면접질문을 알려주었음', 227, '2020-11-19');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '포트폴리오 수정을 해주었음', 130, '2020-09-5');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '면접 노하우를 알려주었다', 325, '2020-06-12');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '포트폴리오 수정을 해주었음', 263, '2020-06-6');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '자소서 수정을 해주었음', 62, '2020-09-27');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '포트폴리오 수정을 해주었음', 34, '2020-08-1');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '포트폴리오 수정을 해주었음', 375, '2020-11-29');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '면접 태도에 대한 교정', 98, '2020-07-29');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '자소서 수정을 해주었음', 161, '2020-10-29');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '면접 태도에 대한 교정', 173, '2020-07-5');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '포트폴리오 수정을 해주었음', 238, '2020-09-7');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '면접 노하우를 알려주었다', 29, '2020-09-18');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '포트폴리오 수정을 해주었음', 31, '2020-07-3');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '면접 노하우를 알려주었다', 267, '2020-07-18');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '자소서 수정을 해주었음', 123, '2020-06-24');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '포트폴리오 수정을 해주었음', 86, '2020-10-29');
Insert into tblJobConsultation (seq, content, regiNum, consDate) values (SEQJOBCONSULTATION.nextval, '면접 태도에 대한 교정', 217, '2020-09-13');


