select * from tblLinkCompany;
--rollback;

create sequence seqLinkCompany;

insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '에스케이플래닛(주)', '경기도 성남시 분당구 판교로 264(삼평동)', '데이터분석팀', 4000);
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '(주)우아한형제들', '서울시 송파구 위례성대로 2', '백엔드개발팀', 3200);
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '(주)씨젠', '서울시 송파구 오금로 91', 'SW개발팀', 3800);
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '(주)티몬', '서울시 강남구 테헤란로114길 38', '개발관리팀', 3500);
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '(주)세라젬', '충남 천안시 서북구 정자1길 10', 'APP통합개발팀', 3300);
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '광동제약(주)', '서울시 서초구 서초중앙로 85', 'IT전략팀', 3100);
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '(주)하나투어', '서울시 종로구 인사동5길 41', 'App개발팀', 3100);
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '(주)하나금융티아이', '인천 서구 에코로 167', 'SI개발팀', 3000);
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '(주)넷코아테크', '서울시 성동구 성수일로 77', 'NW보안팀', 2800);
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '(주)산하정보기술', '서울시 금천구 디지털로9길 68', 'JAVA개발팀', 2800);

insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '에스넷시스템(주)', '서울 강남구 선릉로514', '영업팀', '5000');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '(주)델레오코리아', '서울 강남구 테헤란로87길', '품질팀', '4800');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '(주)포시에스', '서울 강남구 논현로 646', '영업팀', '4000');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '메가존클라우드(주)', '서울 강남구 논현로85길 46', '데이터분석팀', '4400');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '(주)인텔리빅스', '서울 서초구 효령로34길 4', '사업부', '3400');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '(주)아로마티카', '서울 강남구 도산대로1길 62', 'IT기획부', '3400');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '(주)페이타랩', '부산 부산진구 서면로 39', 'iOS개발팀', '3700');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '(주)에프에스솔루션', '서울 송파구 법원로11길 11', '개발팀', '3800');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '에스케이인포섹(주)', '경기 성남시 분당구 판교로227번길 23', 'IT영업', '4100');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '(주)바이애틱', '경기 안양시 동안구 흥안대로427번길 16', '백엔드개발팀', '4000');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '(주)리얼시큐', '부산 해운대구 센텀북대로 60', 'SW개발팀', '3000');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '(주)하림지주', '전북 익산시 중앙로 121', 'SI개발팀', '3100');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '(주)미래엔', '서울 서초구 신반포로 321', '데이터분석팀', '2900');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '(주)푸른상호저축은행', '서울 서초구 강남대로 581', '개발관리팀', '2500');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '(주)인터코스코리아', '경기 오산시 가장산업서북로 40-38', 'APP통합개발팀', '2700');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '(주)녹십자셀', '경기 용인시 기흥구 이현로30번길 93', '보안팀', '2600');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '(주)하나투어', '서울 종로구 인사동5길 41', '유지관리팀', '4900');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '(주)윈즈시스템 ', '경기 성남시 분당구 판교로255번길 58', '기술지원팀', '4200');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '(주)서플러스글로벌', '경기 오산시 경기대로 78-26', '보안팀', '3000');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '(주)키스템프', '서울 중구 을지로5길 16', 'SI개발팀', '4900');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, 'AJ네트웍스(주)', '서울 송파구 정의로8길 9', '데이터분석팀', '4800');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '(주)디스트릭트홀딩스', '서울 강남구 테헤란로87길 29', '개발관리팀', '3100');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '(주)케이닥스', '서울 강남구 테헤란로 123', 'APP통합개발팀', '3200');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '이제너두(주)', '서울 강남구 강남대로 262', '데이터분석팀', '2700');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '(주)비바리퍼블리카', '서울 강남구 테헤란로 142', '사업부', '3100');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '(주)엠엘소프트', '경기 과천시 별양로 28', 'IT기획부', '2300');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '(주)참존글로벌워크', '서울 서초구 바우뫼로 150', '영업팀', '4600');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '제이티저축은행(주)', '경기 성남시 분당구 황새울로 324', '품질팀', '4900');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '서울데이타통신(주)', '서울 마포구 와우산로 20', '영업팀', '4100');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '(주)삼천리모터스', '충북 청주시 흥덕구 가로수로754번길 15', 'SI개발팀', '4200');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '(주)비에이치씨', '서울 송파구 올림픽로 299', '데이터분석팀', '4100');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '(주)에이젝코리아', '서울 중구 소월로 10', '개발관리팀', '3500');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '(주)에이티세미콘', '경기 이천시 서이천로 138', 'APP통합개발팀', '4200');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '(주)서울옥션', '서울 종로구 평창30길 24', '데이터분석팀', '3200');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '(주)대교', '서울 관악구 보라매로3길 23', '사업부', '3800');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '(주)NE능률', '서울 마포구 월드컵북로 396', 'IT기획부', '3100');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '(주)포스텍', '경남 창원시 의창구 중앙대로228번길 6', '영업팀', '4500');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '(주)유아이에스', '대전 유성구 테크노3로 65', '품질팀', '4100');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '(주)비즈테크파트너스', '서울 마포구 매봉산로 75', '영업팀', '4700');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '(주)동훈아이텍', '서울 강남구 역삼로 225', 'SI개발팀', '2400');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '(주)페이타랩', '부산 부산진구 서면로 39', '데이터분석팀', '3400');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '(주)리치빔', '서울 송파구 오금동 121-3', '개발관리팀', '2800');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '(주)칸테크', '서울 금천구 가산디지털2로 30', 'APP통합개발팀', '2600');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '인크로스(주)', '서울 관악구 남부순환로 1926', '보안팀', '3800');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '(주)코-멕', '경기 평택시 평택항만길 348', '유지관리팀', '3500');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '유안타증권(주)', '서울 중구 을지로 76', '솔루션팀', '2600');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '(주)씨앤씨', '충북 청주시 흥덕구 과학산업4로 9', '사무지원팀', '4800');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '(주)이커머스테크', '서울 마포구 월드컵북로54길 11', '모바일개발팀', '3100');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '(주)서한', '대구 수성구 명덕로 415', 'SI개발팀', '2700');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '대림비앤코(주)', '경남 창원시 성산구 공단로 52', '데이터분석팀', '3400');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '(주)야놀자', '서울 강남구 테헤란로108길 42', '개발관리팀', '2400');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '그루미', '서울 강남구 역삼동 637-24', 'APP통합개발팀', '4400');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '템프인(주)', '서울 관악구 봉천로 359', '보안팀', '3600');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '휴머레인컨설팅', '서울 서초구 서초동 1330-3', '유지관리팀', '3800');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '(주)빗썸코리아', '서울 강남구 테헤란로 124', '솔루션팀', '4000');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '(주)스타랩스', '서울 강남구 테헤란로25길 6-9', '사무지원팀', '2700');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '(주)비브릭', '서울 강남구 도산대로 317', '모바일개발팀', '3100');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '코코넛사일로(주)', '서울 성북구 화랑로14길 5', '개발관리팀', '2200');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '(주)드림에이치알', '서울 서초구 서초대로62길 9-22', 'APP통합개발팀', '3600');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '(주)키스템프', '서울 중구 을지로5길 16', '데이터분석팀', '3900');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '(주)신성씨앤에스', '서울 금천구 가산디지털1로 19', '사업부', '2200');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '(주)엔잡얼라이언스', '서울 금천구 가산디지털1로 233', '데이터분석팀', '2800');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '(주)모간', '대구 달성군 논공중앙로46길 27', '사업부', '3900');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '서울데이타통신(주)', '서울 마포구 와우산로 20', 'IT기획부', '2300');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '농심엔지니어링(주)', '서울 동작구 여의대방로 112', '데이터분석팀', '3300');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '정우산기(주)', '충남 천안시 동남구 5산단로 253', '사업부', '4400');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '(주)휴먼코아', '서울 송파구 법원로 128', 'IT기획부', '3000');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '토모도모(주)', '서울 종로구 사직로 130', 'iOS개발팀', '4300');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '(주)온결', '서울 강남구 봉은사로30길', '개발팀', '4200');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '온시큐리티(주)', '서울 송파구 송파대로 167', 'IT영업', '3400');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '(주)린켐코리아', '경기 평택시 원한산길 143', '백엔드개발팀', '4600');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '미디어텍코리아(주)', '경기 성남시 분당구 황새울로 216', 'SW개발팀', '2900');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '(주)지욥', '서울 강서구 마곡중앙6로 45', 'SI개발팀', '3700');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '(주)에이모', '경기 성남시 분당구 판교로228번길 17', '사업부', '3600');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '(주)애드디에스', '대구 중구 국채보상로 726', '데이터분석팀', '4700');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '반석써치(주)', '서울 강남구 테헤란로64길', '사업부', '4000');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '(주)네오디에스', '경기 성남시 중원구 성남대로 985', 'IT기획부', '4000');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '(주)제이엔테크놀러지', '서울 구로구 디지털로26길 61', 'iOS개발팀', '2400');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '(주)엠제이인스텍', '서울 마포구 만리재로 15', '개발팀', '3600');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '(주)서진정보기술', '대구 달서구 달서대로 559', 'IT영업', '2200');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '(주)아데코코리아', '서울 송파구 백제고분로 69', '백엔드개발팀', '3500');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '(주)엠엘소프트', '경기 과천시 별양로 28', 'SW개발팀', '4700');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '(주)에이치엘엠씨 ', '서울 중구 소공로 116', 'SI개발팀', '4300');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '현대엠엔소프트', '서울 용산구 원효로 74', '영업팀', '3500');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '(주)푸드나무', '서울 마포구 월드컵북로 396', '품질팀', '2900');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '(주)바른인사컨설팅', '서울 구로구 디지털로26길 123', '영업팀', '2500');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '알비소프트(주)', '서울 성동구 성수일로10길 26', '유지관리팀', '3800');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '(주)파마엔텍', '경기 용인시 기흥구 흥덕1로 13', '솔루션팀', '2800');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '코드크레인', '서울 마포구 성암로 17', '사무지원팀', '4500');
insert into tblLinkCompany(seq, name, address, department, salary) values (seqLinkCompany.nextVal, '(주)피플케어코리아', '서울 강남구 영동대로 511', '빅데이터팀', '2700');






